// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfenqvpewmawzqfrtycj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmZW5xdnBld21hd3pxZnJ0eWNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjE4MTEsImV4cCI6MjA3MDczNzgxMX0.gmWG9uErhpIO_0iO9ohEbJeuYwOUHtGypxJTNzJzwKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});